import Strategy from './strategy';
import Observer from './observer';
import Decorator from './decorator';
import SimpleFactory from './factory/simple-factory';
import FactoryMethod from './factory/factory-method';
import AbstractFactory from './factory/abstract-factory';
import Singleton from './singleton';
import Command from './command';
import Adapter from './adapter';
import Facade from './facade';
import TemplateMethod from './template-method';
import Iterator from './iterator';
import Composite from './composite';
import State from './state';
import Proxy from './proxy';

Strategy();
Observer();
Decorator();
SimpleFactory();
FactoryMethod();
AbstractFactory();
Singleton();
Command();
Adapter();
Facade();
TemplateMethod();
Iterator();
Composite();
State();
Proxy();
